<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LI9TG70" failures="1" tests="5" name="test" time="75.026" errors="0" timestamp="2022-10-02T22:46:16 EDT">
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="emptyPasswordTC1" time="8.421">
    <failure type="java.lang.AssertionError" message="expected [Please enter your] but found [Please enter your password.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your] but found [Please enter your password.]
at com.salesforce.automation.scripts.TestScripts.emptyPasswordTC1(TestScripts.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- emptyPasswordTC1 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="loginSuccessTC2" time="9.757"/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="logoutSuccessTC3" time="0.0">
    <skipped/>
  </testcase> <!-- logoutSuccessTC3 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="forgotPasswordTC4A" time="4.892"/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="invalidLoginTC4B" time="8.797"/>
  <testcase classname="com.salesforce.automation.basetest.BaseAutomation" name="browserSel" time="0.0">
    <ignored/>
  </testcase> <!-- browserSel -->
</testsuite> <!-- test -->
