<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LI9TG70" failures="1" tests="5" name="test" time="80.947" errors="0" timestamp="2022-11-09T00:14:47 EST">
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="emptyPasswordTC1" time="6.645">
    <failure type="java.lang.AssertionError" message="expected [Please enter your] but found [Please enter your password.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your] but found [Please enter your password.]
at com.salesforce.automation.scripts.TestScripts.emptyPasswordTC1(TestScripts.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- emptyPasswordTC1 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="loginSuccessTC2" time="15.263"/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="logoutSuccessTC3" time="0.0">
    <skipped/>
  </testcase> <!-- logoutSuccessTC3 -->
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="forgotPasswordTC4A" time="5.229"/>
  <testcase classname="com.salesforce.automation.scripts.TestScripts" name="invalidLoginTC4B" time="6.2"/>
  <testcase classname="com.salesforce.automation.basetest.BaseAutomation" name="browserSel" time="0.0">
    <ignored/>
  </testcase> <!-- browserSel -->
</testsuite> <!-- test -->
